#Makes clib7zip_test
P7ZIPSOURCE=p7zip_9.20.1
CXXFLAGS=\
	-I. \
	-I$(P7ZIPSOURCE)/CPP \
	-I$(P7ZIPSOURCE)/CPP/7zip/UI/Client7z \
	-I$(P7ZIPSOURCE)/CPP/myWindows \
	-I$(P7ZIPSOURCE)/CPP/include_windows \
	-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE \
	-DUNICODE -D_UNICODE

CFLAGS=\
	-I$(P7ZIPSOURCE)/CPP \
	-I$(P7ZIPSOURCE)/CPP/7zip/UI/Client7z \
	-I$(P7ZIPSOURCE)/CPP/myWindows \
	-I$(P7ZIPSOURCE)/CPP/include_windows \
	-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_REENTRANT \
	-DUNICODE -D_UNICODE

LDFLAGS=-ldl -lpthread

	#$(P7ZIPSOURCE)/CPP/Common/MyWindows.o \
	#$(P7ZIPSOURCE)/CPP/Windows/PropVariant.o
PROG=clib7zip_test
OBJS= \
	clib7zip.o \
	clib7zip_test.o \
	$(P7ZIPSOURCE)/CPP/myWindows/wine_date_and_time.o \
	$(P7ZIPSOURCE)/CPP/myWindows/myGetTickCount.o \
	$(P7ZIPSOURCE)/CPP/Common/CRC.o \
	$(P7ZIPSOURCE)/CPP/Common/IntToString.o \
	$(P7ZIPSOURCE)/CPP/Common/MyMap.o \
	$(P7ZIPSOURCE)/CPP/Common/MyString.o \
	$(P7ZIPSOURCE)/CPP/Common/MyWindows.o \
	$(P7ZIPSOURCE)/CPP/Common/MyXml.o \
	$(P7ZIPSOURCE)/CPP/Common/StringConvert.o \
	$(P7ZIPSOURCE)/CPP/Common/StringToInt.o \
	$(P7ZIPSOURCE)/CPP/Common/UTFConvert.o \
	$(P7ZIPSOURCE)/CPP/Common/MyVector.o \
	$(P7ZIPSOURCE)/CPP/Common/Wildcard.o \
	$(P7ZIPSOURCE)/CPP/Windows/FileDir.o \
	$(P7ZIPSOURCE)/CPP/Windows/FileFind.o \
	$(P7ZIPSOURCE)/CPP/Windows/FileIO.o \
	$(P7ZIPSOURCE)/CPP/Windows/PropVariant.o \
	$(P7ZIPSOURCE)/CPP/Windows/PropVariantUtils.o \
	$(P7ZIPSOURCE)/CPP/Windows/Synchronization.o \
	$(P7ZIPSOURCE)/CPP/Windows/System.o \
	$(P7ZIPSOURCE)/CPP/Windows/Time.o \
	$(P7ZIPSOURCE)/CPP/7zip/Common/InBuffer.o \
	$(P7ZIPSOURCE)/CPP/7zip/Common/InOutTempBuffer.o \
	$(P7ZIPSOURCE)/CPP/7zip/Common/CreateCoder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Common/CWrappers.o \
	$(P7ZIPSOURCE)/CPP/7zip/Common/FilterCoder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Common/LimitedStreams.o \
	$(P7ZIPSOURCE)/CPP/7zip/Common/LockedStream.o \
	$(P7ZIPSOURCE)/CPP/7zip/Common/MethodId.o \
	$(P7ZIPSOURCE)/CPP/7zip/Common/MethodProps.o \
	$(P7ZIPSOURCE)/CPP/7zip/Common/MemBlocks.o \
	$(P7ZIPSOURCE)/CPP/7zip/Common/OffsetStream.o \
	$(P7ZIPSOURCE)/CPP/7zip/Common/OutBuffer.o \
	$(P7ZIPSOURCE)/CPP/7zip/Common/OutMemStream.o \
	$(P7ZIPSOURCE)/CPP/7zip/Common/ProgressMt.o \
	$(P7ZIPSOURCE)/CPP/7zip/Common/ProgressUtils.o \
	$(P7ZIPSOURCE)/CPP/7zip/Common/StreamBinder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Common/StreamObjects.o \
	$(P7ZIPSOURCE)/CPP/7zip/Common/StreamUtils.o \
	$(P7ZIPSOURCE)/CPP/7zip/Common/VirtThread.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/ArchiveExports.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/DllExports2.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/ApmHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/ArjHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Bz2Handler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/CpioHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/CramfsHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/DebHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/DeflateProps.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/DmgHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/ElfHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/FatHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/FlvHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/GzHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/LzhHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/LzmaHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/MachoHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/MbrHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/MslzHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/MubHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/NtfsHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/PeHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/PpmdHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/RpmHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/SplitHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/SquashfsHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/SwfHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/VhdHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/XarHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/XzHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/ZHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Common/CoderMixer2.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Common/CoderMixer2MT.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Common/CrossThreadProgress.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Common/DummyOutStream.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Common/FindSignature.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Common/InStreamWithCRC.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Common/ItemNameUtils.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Common/MultiStream.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Common/OutStreamWithCRC.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Common/OutStreamWithSha1.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Common/HandlerOut.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Common/ParseProperties.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/7z/7zCompressionMode.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/7z/7zDecode.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/7z/7zEncode.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/7z/7zExtract.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/7z/7zFolderInStream.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/7z/7zFolderOutStream.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/7z/7zHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/7z/7zHandlerOut.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/7z/7zHeader.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/7z/7zIn.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/7z/7zOut.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/7z/7zProperties.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/7z/7zSpecStream.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/7z/7zUpdate.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/7z/7zRegister.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Cab/CabBlockInStream.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Cab/CabHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Cab/CabHeader.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Cab/CabIn.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Cab/CabRegister.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Chm/ChmHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Chm/ChmHeader.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Chm/ChmIn.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Chm/ChmRegister.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Com/ComHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Com/ComIn.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Com/ComRegister.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Hfs/HfsHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Hfs/HfsIn.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Hfs/HfsRegister.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Iso/IsoHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Iso/IsoHeader.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Iso/IsoIn.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Iso/IsoRegister.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Nsis/NsisDecode.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Nsis/NsisHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Nsis/NsisIn.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Nsis/NsisRegister.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Rar/RarHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Rar/RarHeader.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Rar/RarIn.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Rar/RarItem.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Rar/RarVolumeInStream.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Rar/RarRegister.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Tar/TarHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Tar/TarHandlerOut.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Tar/TarHeader.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Tar/TarIn.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Tar/TarOut.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Tar/TarRegister.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Tar/TarUpdate.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Udf/UdfHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Udf/UdfIn.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Udf/UdfRegister.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Wim/WimHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Wim/WimHandlerOut.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Wim/WimIn.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Wim/WimRegister.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Zip/ZipAddCommon.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Zip/ZipHandler.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Zip/ZipHandlerOut.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Zip/ZipHeader.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Zip/ZipIn.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Zip/ZipItem.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Zip/ZipOut.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Zip/ZipUpdate.o \
	$(P7ZIPSOURCE)/CPP/7zip/Archive/Zip/ZipRegister.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/CodecExports.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/ArjDecoder1.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/ArjDecoder2.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/Bcj2Coder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/Bcj2Register.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/BcjCoder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/BcjRegister.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/BitlDecoder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/BranchCoder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/BranchMisc.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/BranchRegister.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/ByteSwap.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/BZip2Crc.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/BZip2Decoder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/BZip2Encoder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/BZip2Register.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/CopyCoder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/CopyRegister.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/Deflate64Register.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/DeflateDecoder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/DeflateEncoder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/DeflateRegister.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/DeltaFilter.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/Lzma2Decoder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/Lzma2Encoder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/Lzma2Register.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/ImplodeDecoder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/ImplodeHuffmanDecoder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/LzhDecoder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/LzmaDecoder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/LzmaEncoder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/LzmaRegister.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/LzOutWindow.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/Lzx86Converter.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/LzxDecoder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/PpmdDecoder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/PpmdEncoder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/PpmdRegister.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/PpmdZip.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/QuantumDecoder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/ShrinkDecoder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/ZlibDecoder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/ZlibEncoder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Compress/ZDecoder.o \
	$(P7ZIPSOURCE)/CPP/7zip/Crypto/7zAes.o \
	$(P7ZIPSOURCE)/CPP/7zip/Crypto/7zAesRegister.o \
	$(P7ZIPSOURCE)/CPP/7zip/Crypto/HmacSha1.o \
	$(P7ZIPSOURCE)/CPP/7zip/Crypto/MyAes.o \
	$(P7ZIPSOURCE)/CPP/7zip/Crypto/Pbkdf2HmacSha1.o \
	$(P7ZIPSOURCE)/CPP/7zip/Crypto/RandGen.o \
	$(P7ZIPSOURCE)/CPP/7zip/Crypto/Sha1.o \
	$(P7ZIPSOURCE)/CPP/7zip/Crypto/WzAes.o \
	$(P7ZIPSOURCE)/CPP/7zip/Crypto/Rar20Crypto.o \
	$(P7ZIPSOURCE)/CPP/7zip/Crypto/RarAes.o \
	$(P7ZIPSOURCE)/CPP/7zip/Crypto/ZipCrypto.o \
	$(P7ZIPSOURCE)/CPP/7zip/Crypto/ZipStrong.o \
	$(P7ZIPSOURCE)/C/7zCrc.o \
	$(P7ZIPSOURCE)/C/7zBuf2.o \
	$(P7ZIPSOURCE)/C/7zStream.o \
	$(P7ZIPSOURCE)/C/Aes.o \
	$(P7ZIPSOURCE)/C/Alloc.o \
	$(P7ZIPSOURCE)/C/Bra.o \
	$(P7ZIPSOURCE)/C/Bra86.o \
	$(P7ZIPSOURCE)/C/BraIA64.o \
	$(P7ZIPSOURCE)/C/BwtSort.o \
	$(P7ZIPSOURCE)/C/Delta.o \
	$(P7ZIPSOURCE)/C/HuffEnc.o \
	$(P7ZIPSOURCE)/C/LzFind.o \
	$(P7ZIPSOURCE)/C/LzFindMt.o \
	$(P7ZIPSOURCE)/C/Lzma2Dec.o \
	$(P7ZIPSOURCE)/C/Lzma2Enc.o \
	$(P7ZIPSOURCE)/C/LzmaDec.o \
	$(P7ZIPSOURCE)/C/LzmaEnc.o \
	$(P7ZIPSOURCE)/C/MtCoder.o \
	$(P7ZIPSOURCE)/C/Ppmd7.o \
	$(P7ZIPSOURCE)/C/Ppmd7Dec.o \
	$(P7ZIPSOURCE)/C/Ppmd7Enc.o \
	$(P7ZIPSOURCE)/C/Ppmd8.o \
	$(P7ZIPSOURCE)/C/Ppmd8Dec.o \
	$(P7ZIPSOURCE)/C/Ppmd8Enc.o \
	$(P7ZIPSOURCE)/C/Sha256.o \
	$(P7ZIPSOURCE)/C/Sort.o \
	$(P7ZIPSOURCE)/C/Xz.o \
	$(P7ZIPSOURCE)/C/XzCrc64.o \
	$(P7ZIPSOURCE)/C/XzDec.o \
	$(P7ZIPSOURCE)/C/XzEnc.o \
	$(P7ZIPSOURCE)/C/XzIn.o \
	$(P7ZIPSOURCE)/C/7zCrc.o \
	$(P7ZIPSOURCE)/C/7zCrcOpt.o \
	$(P7ZIPSOURCE)/C/Threads.o

all: clib7zip_test
$(PROG): $(OBJS)
%: %.o
	$(CXX) $(LDFLAGS) $^ -o $@

clean:
	rm -f $(PROG) $(OBJS)
